services:
  - type: web
    name: tradesman-handy-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /api/v1/health
    autoDeploy: true
